Optional confirmations, transcript sending, and a default topic.
eartharoid/DiscordTickets pull request #80
Opened 2020-12-21 02:15 UTC by FivePixels

#### Information

- [ ] This includes major changes (breaking changes)
- [x] This includes minor changes (minimal usage changes, minor new features)
- [ ] This includes patches (bug fixes, documentation changes etc)

#### Is this related to an issue?
No.
#### Changes made

I added a few options for the user to make their DiscordTickets bot more streamline and more configurable. In my use case, these changes will be extremely useful to prevent users from committing actions I'd ask them not to do.

These options include: 

- Return confirmation on close command.
- Disable/Enable transcript sending to the ticket creator.
- Return confirmation on delete command.
- Disable/Enable the new command. 

The `-close` and `-delete` commands now have the option to return a confirmation. 
The user can decide if they would like to send transcripts to ticket creators.

Also included:
- Default topic when none is provided.

When the `-new` command isn't provided a second argument, the `default_topic` config item will be filled into the topic. This also works with panels, so panels can be provided a default topic.

#### Confirmations

- [ ] I have updated any necessary documentation
- [x] This uses consistent code style
- [x] This is tested and works

Documentation that hasn't been updated, and cannot be updated by me, is on the wiki.

2020-12-21 11:15 UTC, eartharoid requested changes
There's a mistake starting at line [79](https://github.com/eartharoid/DiscordTickets/pull/80/files#diff-5263c4286e7334e2ab45b9b0ab9b07efc02a0941c867e6f03e2bd798e3f704f9R79) in `new.js` - it should be:
```js
} else if (topic.length < 1) {
	if (!/("|'|`)("|'|`)/.test(config.default_topic)) {
		topic = config.default_topic;
	} else {
		topic = 'No topic given';
	}
}
```
However, I don't like how the default topic option is implemented, I think it would be better you kept it as before. but instead of:
```js
else if (topic.length < 1) topic = 'No topic given';
```
use:
```js
else if (topic.length < 1) topic = config.tickets.default_topic;
```
and move `default_topic` to `tickets.default_topic`.
or:
```js
// user/config.js
tickets: {
// . . .
  default_topic: {
    command: 'No topic given',
    panel: 'Created via panel'
  }
}
```

2020-12-21 16:39 UTC, FivePixels commented
I changed the files you requested.

2021-01-01 15:19 UTC, eartharoid reviewed
I don't understand the purpose of the `commands.close.send_transcripts` option in the config. The bot checks if transcripts are enabled and it only sends the message if either web or text transcripts are enabled. It would make sense if it only toggled sending transcripts to the ticket creator in DMs, but it appears to also toggle sending the message to the archives channel, making the option redundant.

2021-01-01 15:43 UTC, eartharoid approved these changes
Thank you.

2021-01-01 15:43 UTC, merged